module.exports = {
  PATH_FRANCHISE: '../franchise_picture',
  PATH_PICTURE: '../branch_picture',
  PATH_COVER: '../branch_cover',
  PATH_SLIP: '../slip_picture',
  PATH_MACHINETYPE: '../machinetype_picture',
  PATH_MACHINETYPEFILE: '../../program',
  PATH_SETTINGMACHINE: '../../setting_machine',
  PATH_MAINTENANCE: '../maintenance_picture',
  PATH_MARKER: '../chatbot/assets',
  PATH_SENDIMAGE: '../sendimage',
  URL_FRANCHISE: 'https://ipstthailand.com/noomanee/franchise_picture',
  URL_PICTURE: 'https://ipstthailand.com/noomanee/branch_picture',
  URL_COVER: 'https://ipstthailand.com/noomanee/branch_cover',
  URL_SLIP: 'https://ipstthailand.com/noomanee/slip_picture',
  URL_MACHINETYPE: 'https://ipstthailand.com/noomanee/machinetype_picture',
  URL_MACHINETYPEFILE: 'https://ipstthailand.com/program',
  URL_SETTINGMACHINE: 'https://ipstthailand.com/setting_machine',
  URL_MAINTENANCE: 'https://ipstthailand.com/noomanee/maintenance_picture',
  URL_MARKER: 'https://ipstthailand.com/noomanee/chatbot/assets',
  URL_SENDIMAGE: 'https://ipstthailand.com/noomanee/sendimage',
  ERROR_CODE_API: '000',
  ERROR_CODE_DATABASE: '001',
  ERROR_CODE_INVALID: '002',
  ERROR_CODE_NO_DATA: '003',
  ERROR_CODE_LOGIN: '004',
  ERROR_CODE_PRIVILEGE: '005',
  ERROR_CODE_UPLOAD: '006',
  ERROR_CODE_POINT_TIMEOUT: '007',
  ERROR_CODE_POINT_USE: '008',
  ERROR_CODE_RESIVE_CODE: '009',
  ERROR_CODE_RESIVE_HOUR_MORE: '010',
  ERROR_CODE_BOX_NOT_FOUND_USER: '011',

  ERROR_INVALID: 'ข้อมูลไม่ถูกต้อง',
  ERROR_NO_DATA: 'ไม่มีข้อมูล',
  ERROR_LOGIN: 'Username หรือ Password ไม่ถูกต้อง',
  ERROR_TIMEOUT: 'หมดเวลาการเชื่อมต่อ กรุณา Login ใหม่อีกครั้ง',
  ERROR_PRIVILEGE: 'ไม่มีสิทธิ์ แก้ไขข้อมูล',
  ERROR_POINT_TIMEOUT: 'หมดเวลาการทำรายการ',
  ERROR_POINT_USE: 'คะแนนสะสมไม่พอใช้งาน',
  ERROR_RESIVE_CODE: 'รหัสตู้และรหัสรับของไม่ตรงกัน',
  ERROR_RESIVE_HOUR_MORE: 'ระยะเวลาฝากเกิน',
  ERROR_BOX_NOT_FOUND_USER: 'ยังไม่ได้ยืนยันตัวตน',
};
